# Generated by Django 5.0.2 on 2024-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('Architecture', 'Architecture'), ('Designers', 'Designers'), ('Electricians', 'Electricians'), ('Furniture', 'Furniture'), ('Plumbers', 'Plumbers')], max_length=55)),
            ],
        ),
    ]
