# Generated by Django 5.0.2 on 2024-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contract_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_details',
            name='category',
        ),
        migrations.AlterField(
            model_name='contract_details',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
