# Generated by Django 5.0.2 on 2024-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contract_details_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='name',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
