# Generated by Django 5.0.2 on 2024-02-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_works_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contract_details',
        ),
        migrations.DeleteModel(
            name='workers',
        ),
    ]
