# Generated by Django 5.0.2 on 2024-02-17 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_contract_details_delete_workers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('Architecture', 'Architecture'), ('Designers', 'Designers'), ('Electricians', 'Electricians'), ('Furniture', 'Furniture'), ('Plumbers', 'Plumbers')], max_length=55)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contract_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='home.works')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='home.workers')),
            ],
        ),
    ]
