# Generated by Django 5.0.2 on 2024-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_workers_contract_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_details',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
